### ISSUE TITLE
Remove _palettes.scss

### ISSUE THREAD

**Issue by zeevo** [bluehalo/ngx-starter#214]
Hello

I suggest we move away from the `_palettes.scss` pattern, and replace all variables in `_colors.scss` with their values directly. I have three reasons for why this makes more sense.

1.  If teams are really using all of those different colors of the palette in their components, then their app is *probably* inconsistent and not following UX guidelines
2.  If you are overriding variables in `_colors.scss` using values from the palette and your UX team gives you colors that aren't in the palette, then you end up sticking values inside the palette all over the place, and then pulling them back out in `_colors.scss`, defeating the purpose of the palettes.
3. Sometimes you need more than 5 colors of a particular color. For example, I want many different grays-- Not just a default, two light ones, and two dark ones given by the `mat-palette` pattern.

I think it is simpler to just have `_colors.scss` and overrides for colors with their direct values instead of going through accessing values from palettes.

What do we think?

**Comment by lu-c** [comment]
Hi, would like to address some of your points!

1. **All the colors of the rainbow**: it's not intended for any app to be using all of these different colors, but to just provide some default palettes for the user to quickly replace in their `_colors.scss` file to speed up development - Since they're scss variables, they'll get compiled out and won't affect the final css in the site. The intention of the palettes is to have forked apps just pick a quick color, but in reality, I think everyone has been generating their own palettes instead. I think it could be worth working with the UX team to see if can get them to generate a set of generic palettes and stick to them

2. **Overriding variables**: If the colors arent in the palette, can you generate a custom palette? I might be alone here, but I don't feel like we should need to accomodate overriding variables for colors from the palettes file.

3. **Not enough colors**: Depending on the usage, I am also curious how these are necessary - These color declarations are meant to cover the main theme of the site, right? Specific colors for elements in a component should be handled on the project level, and not the starter. When I added the color system to the starter, I actually took these color design concepts from material design - and their recommendation was to have only 3 shades (default, light, dark) for 2 palettes (primary, and secondary). They didn't recommend using more than that because you need to have enough variation between the colors to be recognizable and distinct, and also not to overwhelm the user with too many colors.

4. The other thing is that material design suggested having separate palettes to define more variables: backgrounds, surfaces, errors, typography, and iconography. Maybe we could consider adding these instead, if there are not enough colors to go around?
