### ISSUE TITLE
Left navigation menu item overlap on small resolutions

### ISSUE THREAD

**Issue by brianghig** [bluehalo/ngx-starter#9]
When the screen height is sufficiently reduced, the bottom menu items will overlap with any top menu items, as seen in the screen shot below.

<img width="54" alt="screen shot 2018-11-02 at 7 28 49 am" src="https://user-images.githubusercontent.com/297404/47913061-103e7700-de71-11e8-9642-d4a26bd3c5f6.png">

**Comment by reblace** [comment]
What would we like the behavior to be? I see a couple options:

- Min height on the left bar so it scrolls with the page once it gets to some minimum height. We'd still have the issue where if there are enough icons, you'd have to change the min height to ensure they don't overlap.
- Opaque backgrounds for the icons and set a deliberate z-order so that the account icons draw on top of the other icons, but do so in a less broken looking way.

Or, we can do some combination of the two. Any other ideas? I'd suggest we stay away from overly complicated solutions like dynamically appearing/disappearing icons or collapsing to a hamburger menu just cause cases where the menu gets this small are pretty rare and I think it's ok for the functionality to degrade a little bit when the window is this small.

**Comment by brianghig** [comment]
@reblace I'm in favor of the minimum height idea on the left bar, or even letting the left bar provide a scroll if its contents go past some minimum height. With that, I'm wondering what some of our min heights would be if we consider mobile device use and the generally expected experience on that platform. Maybe that's where a hamburger menu makes sense? Or dual scrolling the page and left bar based on that min height?
